# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from mlx_native_scamp.distributed.proto import scamp_worker_v1_pb2 as mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2


class ScampWorkerStub(object):
    """Version 1 of the Apple/MLX worker protocol. Every request carries the API
    version so incompatible workers fail explicitly instead of misreading work.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/mlx_native_scamp.distributed.v1.ScampWorker/GetCapabilities',
                request_serializer=mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.VersionRequest.SerializeToString,
                response_deserializer=mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.WorkerCapabilities.FromString,
                )
        self.CheckHealth = channel.unary_unary(
                '/mlx_native_scamp.distributed.v1.ScampWorker/CheckHealth',
                request_serializer=mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.VersionRequest.SerializeToString,
                response_deserializer=mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.WorkerHealth.FromString,
                )
        self.ExecuteProfileTile = channel.unary_unary(
                '/mlx_native_scamp.distributed.v1.ScampWorker/ExecuteProfileTile',
                request_serializer=mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.ProfileTileRequest.SerializeToString,
                response_deserializer=mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.ProfileTileResult.FromString,
                )


class ScampWorkerServicer(object):
    """Version 1 of the Apple/MLX worker protocol. Every request carries the API
    version so incompatible workers fail explicitly instead of misreading work.
    """

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteProfileTile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScampWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.VersionRequest.FromString,
                    response_serializer=mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.WorkerCapabilities.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.VersionRequest.FromString,
                    response_serializer=mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.WorkerHealth.SerializeToString,
            ),
            'ExecuteProfileTile': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteProfileTile,
                    request_deserializer=mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.ProfileTileRequest.FromString,
                    response_serializer=mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.ProfileTileResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mlx_native_scamp.distributed.v1.ScampWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ScampWorker(object):
    """Version 1 of the Apple/MLX worker protocol. Every request carries the API
    version so incompatible workers fail explicitly instead of misreading work.
    """

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mlx_native_scamp.distributed.v1.ScampWorker/GetCapabilities',
            mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.VersionRequest.SerializeToString,
            mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.WorkerCapabilities.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mlx_native_scamp.distributed.v1.ScampWorker/CheckHealth',
            mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.VersionRequest.SerializeToString,
            mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.WorkerHealth.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteProfileTile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mlx_native_scamp.distributed.v1.ScampWorker/ExecuteProfileTile',
            mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.ProfileTileRequest.SerializeToString,
            mlx__native__scamp_dot_distributed_dot_proto_dot_scamp__worker__v1__pb2.ProfileTileResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
